/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppNeedLoginRouteImport } from './routes/_app/needLogin'
import { Route as AppProtectedRouteRouteImport } from './routes/_app/_protected/route'
import { Route as AppArticleArticleIdRouteImport } from './routes/_app/article.$articleId'
import { Route as AppProtectedSubmissionRouteImport } from './routes/_app/_protected/submission'
import { Route as AppProtectedEditorRouteImport } from './routes/_app/_protected/editor'
import { Route as AppProtectedMeSettingsRouteImport } from './routes/_app/_protected/me/settings'
import { Route as AppProtectedMePasswordRouteImport } from './routes/_app/_protected/me/password'
import { Route as AppProtectedMeNotificationsRouteRouteImport } from './routes/_app/_protected/me/notifications/route'
import { Route as AppProtectedMeNotificationsIndexRouteImport } from './routes/_app/_protected/me/notifications/index'
import { Route as AppProtectedProfileUserIdFollowingRouteImport } from './routes/_app/_protected/profile/$userId/following'
import { Route as AppProtectedProfileUserIdFollowersRouteImport } from './routes/_app/_protected/profile/$userId/followers'
import { Route as AppProtectedMeNotificationsLikeRouteImport } from './routes/_app/_protected/me/notifications/like'
import { Route as AppProtectedMeNotificationsFollowRouteImport } from './routes/_app/_protected/me/notifications/follow'
import { Route as AppProtectedArticlesEditArticleIdRouteImport } from './routes/_app/_protected/articles.edit.$articleId'
import { Route as AppProtectedProfileUserIdProfileRouteRouteImport } from './routes/_app/_protected/profile/$userId/_profile/route'
import { Route as AppProtectedProfileUserIdProfileIndexRouteImport } from './routes/_app/_protected/profile/$userId/_profile/index'
import { Route as AppProtectedProfileUserIdListsListIdRouteImport } from './routes/_app/_protected/profile/$userId/lists.$listId'
import { Route as AppProtectedProfileUserIdProfileRepostsRouteImport } from './routes/_app/_protected/profile/$userId/_profile/reposts'
import { Route as AppProtectedProfileUserIdProfileListsRouteImport } from './routes/_app/_protected/profile/$userId/_profile/lists'
import { Route as AppProtectedProfileUserIdProfileActivityRouteImport } from './routes/_app/_protected/profile/$userId/_profile/activity'
import { Route as AppProtectedProfileUserIdProfileAboutRouteImport } from './routes/_app/_protected/profile/$userId/_profile/about'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNeedLoginRoute = AppNeedLoginRouteImport.update({
  id: '/needLogin',
  path: '/needLogin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectedRouteRoute = AppProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticleArticleIdRoute = AppArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectedSubmissionRoute = AppProtectedSubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedEditorRoute = AppProtectedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedMeSettingsRoute = AppProtectedMeSettingsRouteImport.update({
  id: '/me/settings',
  path: '/me/settings',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedMePasswordRoute = AppProtectedMePasswordRouteImport.update({
  id: '/me/password',
  path: '/me/password',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedMeNotificationsRouteRoute =
  AppProtectedMeNotificationsRouteRouteImport.update({
    id: '/me/notifications',
    path: '/me/notifications',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedMeNotificationsIndexRoute =
  AppProtectedMeNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProtectedMeNotificationsRouteRoute,
  } as any)
const AppProtectedProfileUserIdFollowingRoute =
  AppProtectedProfileUserIdFollowingRouteImport.update({
    id: '/profile/$userId/following',
    path: '/profile/$userId/following',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedProfileUserIdFollowersRoute =
  AppProtectedProfileUserIdFollowersRouteImport.update({
    id: '/profile/$userId/followers',
    path: '/profile/$userId/followers',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedMeNotificationsLikeRoute =
  AppProtectedMeNotificationsLikeRouteImport.update({
    id: '/like',
    path: '/like',
    getParentRoute: () => AppProtectedMeNotificationsRouteRoute,
  } as any)
const AppProtectedMeNotificationsFollowRoute =
  AppProtectedMeNotificationsFollowRouteImport.update({
    id: '/follow',
    path: '/follow',
    getParentRoute: () => AppProtectedMeNotificationsRouteRoute,
  } as any)
const AppProtectedArticlesEditArticleIdRoute =
  AppProtectedArticlesEditArticleIdRouteImport.update({
    id: '/articles/edit/$articleId',
    path: '/articles/edit/$articleId',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedProfileUserIdProfileRouteRoute =
  AppProtectedProfileUserIdProfileRouteRouteImport.update({
    id: '/profile/$userId/_profile',
    path: '/profile/$userId',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedProfileUserIdProfileIndexRoute =
  AppProtectedProfileUserIdProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProtectedProfileUserIdProfileRouteRoute,
  } as any)
const AppProtectedProfileUserIdListsListIdRoute =
  AppProtectedProfileUserIdListsListIdRouteImport.update({
    id: '/profile/$userId/lists/$listId',
    path: '/profile/$userId/lists/$listId',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedProfileUserIdProfileRepostsRoute =
  AppProtectedProfileUserIdProfileRepostsRouteImport.update({
    id: '/reposts',
    path: '/reposts',
    getParentRoute: () => AppProtectedProfileUserIdProfileRouteRoute,
  } as any)
const AppProtectedProfileUserIdProfileListsRoute =
  AppProtectedProfileUserIdProfileListsRouteImport.update({
    id: '/lists',
    path: '/lists',
    getParentRoute: () => AppProtectedProfileUserIdProfileRouteRoute,
  } as any)
const AppProtectedProfileUserIdProfileActivityRoute =
  AppProtectedProfileUserIdProfileActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppProtectedProfileUserIdProfileRouteRoute,
  } as any)
const AppProtectedProfileUserIdProfileAboutRoute =
  AppProtectedProfileUserIdProfileAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AppProtectedProfileUserIdProfileRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/needLogin': typeof AppNeedLoginRoute
  '/editor': typeof AppProtectedEditorRoute
  '/submission': typeof AppProtectedSubmissionRoute
  '/article/$articleId': typeof AppArticleArticleIdRoute
  '/me/notifications': typeof AppProtectedMeNotificationsRouteRouteWithChildren
  '/me/password': typeof AppProtectedMePasswordRoute
  '/me/settings': typeof AppProtectedMeSettingsRoute
  '/profile/$userId': typeof AppProtectedProfileUserIdProfileRouteRouteWithChildren
  '/articles/edit/$articleId': typeof AppProtectedArticlesEditArticleIdRoute
  '/me/notifications/follow': typeof AppProtectedMeNotificationsFollowRoute
  '/me/notifications/like': typeof AppProtectedMeNotificationsLikeRoute
  '/profile/$userId/followers': typeof AppProtectedProfileUserIdFollowersRoute
  '/profile/$userId/following': typeof AppProtectedProfileUserIdFollowingRoute
  '/me/notifications/': typeof AppProtectedMeNotificationsIndexRoute
  '/profile/$userId/about': typeof AppProtectedProfileUserIdProfileAboutRoute
  '/profile/$userId/activity': typeof AppProtectedProfileUserIdProfileActivityRoute
  '/profile/$userId/lists': typeof AppProtectedProfileUserIdProfileListsRoute
  '/profile/$userId/reposts': typeof AppProtectedProfileUserIdProfileRepostsRoute
  '/profile/$userId/lists/$listId': typeof AppProtectedProfileUserIdListsListIdRoute
  '/profile/$userId/': typeof AppProtectedProfileUserIdProfileIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AppIndexRoute
  '/needLogin': typeof AppNeedLoginRoute
  '/editor': typeof AppProtectedEditorRoute
  '/submission': typeof AppProtectedSubmissionRoute
  '/article/$articleId': typeof AppArticleArticleIdRoute
  '/me/password': typeof AppProtectedMePasswordRoute
  '/me/settings': typeof AppProtectedMeSettingsRoute
  '/articles/edit/$articleId': typeof AppProtectedArticlesEditArticleIdRoute
  '/me/notifications/follow': typeof AppProtectedMeNotificationsFollowRoute
  '/me/notifications/like': typeof AppProtectedMeNotificationsLikeRoute
  '/profile/$userId/followers': typeof AppProtectedProfileUserIdFollowersRoute
  '/profile/$userId/following': typeof AppProtectedProfileUserIdFollowingRoute
  '/me/notifications': typeof AppProtectedMeNotificationsIndexRoute
  '/profile/$userId/about': typeof AppProtectedProfileUserIdProfileAboutRoute
  '/profile/$userId/activity': typeof AppProtectedProfileUserIdProfileActivityRoute
  '/profile/$userId/lists': typeof AppProtectedProfileUserIdProfileListsRoute
  '/profile/$userId/reposts': typeof AppProtectedProfileUserIdProfileRepostsRoute
  '/profile/$userId/lists/$listId': typeof AppProtectedProfileUserIdListsListIdRoute
  '/profile/$userId': typeof AppProtectedProfileUserIdProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/_protected': typeof AppProtectedRouteRouteWithChildren
  '/_app/needLogin': typeof AppNeedLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/editor': typeof AppProtectedEditorRoute
  '/_app/_protected/submission': typeof AppProtectedSubmissionRoute
  '/_app/article/$articleId': typeof AppArticleArticleIdRoute
  '/_app/_protected/me/notifications': typeof AppProtectedMeNotificationsRouteRouteWithChildren
  '/_app/_protected/me/password': typeof AppProtectedMePasswordRoute
  '/_app/_protected/me/settings': typeof AppProtectedMeSettingsRoute
  '/_app/_protected/profile/$userId/_profile': typeof AppProtectedProfileUserIdProfileRouteRouteWithChildren
  '/_app/_protected/articles/edit/$articleId': typeof AppProtectedArticlesEditArticleIdRoute
  '/_app/_protected/me/notifications/follow': typeof AppProtectedMeNotificationsFollowRoute
  '/_app/_protected/me/notifications/like': typeof AppProtectedMeNotificationsLikeRoute
  '/_app/_protected/profile/$userId/followers': typeof AppProtectedProfileUserIdFollowersRoute
  '/_app/_protected/profile/$userId/following': typeof AppProtectedProfileUserIdFollowingRoute
  '/_app/_protected/me/notifications/': typeof AppProtectedMeNotificationsIndexRoute
  '/_app/_protected/profile/$userId/_profile/about': typeof AppProtectedProfileUserIdProfileAboutRoute
  '/_app/_protected/profile/$userId/_profile/activity': typeof AppProtectedProfileUserIdProfileActivityRoute
  '/_app/_protected/profile/$userId/_profile/lists': typeof AppProtectedProfileUserIdProfileListsRoute
  '/_app/_protected/profile/$userId/_profile/reposts': typeof AppProtectedProfileUserIdProfileRepostsRoute
  '/_app/_protected/profile/$userId/lists/$listId': typeof AppProtectedProfileUserIdListsListIdRoute
  '/_app/_protected/profile/$userId/_profile/': typeof AppProtectedProfileUserIdProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/needLogin'
    | '/editor'
    | '/submission'
    | '/article/$articleId'
    | '/me/notifications'
    | '/me/password'
    | '/me/settings'
    | '/profile/$userId'
    | '/articles/edit/$articleId'
    | '/me/notifications/follow'
    | '/me/notifications/like'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
    | '/me/notifications/'
    | '/profile/$userId/about'
    | '/profile/$userId/activity'
    | '/profile/$userId/lists'
    | '/profile/$userId/reposts'
    | '/profile/$userId/lists/$listId'
    | '/profile/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/needLogin'
    | '/editor'
    | '/submission'
    | '/article/$articleId'
    | '/me/password'
    | '/me/settings'
    | '/articles/edit/$articleId'
    | '/me/notifications/follow'
    | '/me/notifications/like'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
    | '/me/notifications'
    | '/profile/$userId/about'
    | '/profile/$userId/activity'
    | '/profile/$userId/lists'
    | '/profile/$userId/reposts'
    | '/profile/$userId/lists/$listId'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/_protected'
    | '/_app/needLogin'
    | '/_app/'
    | '/_app/_protected/editor'
    | '/_app/_protected/submission'
    | '/_app/article/$articleId'
    | '/_app/_protected/me/notifications'
    | '/_app/_protected/me/password'
    | '/_app/_protected/me/settings'
    | '/_app/_protected/profile/$userId/_profile'
    | '/_app/_protected/articles/edit/$articleId'
    | '/_app/_protected/me/notifications/follow'
    | '/_app/_protected/me/notifications/like'
    | '/_app/_protected/profile/$userId/followers'
    | '/_app/_protected/profile/$userId/following'
    | '/_app/_protected/me/notifications/'
    | '/_app/_protected/profile/$userId/_profile/about'
    | '/_app/_protected/profile/$userId/_profile/activity'
    | '/_app/_protected/profile/$userId/_profile/lists'
    | '/_app/_protected/profile/$userId/_profile/reposts'
    | '/_app/_protected/profile/$userId/lists/$listId'
    | '/_app/_protected/profile/$userId/_profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/needLogin': {
      id: '/_app/needLogin'
      path: '/needLogin'
      fullPath: '/needLogin'
      preLoaderRoute: typeof AppNeedLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/article/$articleId': {
      id: '/_app/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof AppArticleArticleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protected/submission': {
      id: '/_app/_protected/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof AppProtectedSubmissionRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/editor': {
      id: '/_app/_protected/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppProtectedEditorRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/me/settings': {
      id: '/_app/_protected/me/settings'
      path: '/me/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AppProtectedMeSettingsRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/me/password': {
      id: '/_app/_protected/me/password'
      path: '/me/password'
      fullPath: '/me/password'
      preLoaderRoute: typeof AppProtectedMePasswordRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/me/notifications': {
      id: '/_app/_protected/me/notifications'
      path: '/me/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof AppProtectedMeNotificationsRouteRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/me/notifications/': {
      id: '/_app/_protected/me/notifications/'
      path: '/'
      fullPath: '/me/notifications/'
      preLoaderRoute: typeof AppProtectedMeNotificationsIndexRouteImport
      parentRoute: typeof AppProtectedMeNotificationsRouteRoute
    }
    '/_app/_protected/profile/$userId/following': {
      id: '/_app/_protected/profile/$userId/following'
      path: '/profile/$userId/following'
      fullPath: '/profile/$userId/following'
      preLoaderRoute: typeof AppProtectedProfileUserIdFollowingRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/profile/$userId/followers': {
      id: '/_app/_protected/profile/$userId/followers'
      path: '/profile/$userId/followers'
      fullPath: '/profile/$userId/followers'
      preLoaderRoute: typeof AppProtectedProfileUserIdFollowersRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/me/notifications/like': {
      id: '/_app/_protected/me/notifications/like'
      path: '/like'
      fullPath: '/me/notifications/like'
      preLoaderRoute: typeof AppProtectedMeNotificationsLikeRouteImport
      parentRoute: typeof AppProtectedMeNotificationsRouteRoute
    }
    '/_app/_protected/me/notifications/follow': {
      id: '/_app/_protected/me/notifications/follow'
      path: '/follow'
      fullPath: '/me/notifications/follow'
      preLoaderRoute: typeof AppProtectedMeNotificationsFollowRouteImport
      parentRoute: typeof AppProtectedMeNotificationsRouteRoute
    }
    '/_app/_protected/articles/edit/$articleId': {
      id: '/_app/_protected/articles/edit/$articleId'
      path: '/articles/edit/$articleId'
      fullPath: '/articles/edit/$articleId'
      preLoaderRoute: typeof AppProtectedArticlesEditArticleIdRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/profile/$userId/_profile': {
      id: '/_app/_protected/profile/$userId/_profile'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProtectedProfileUserIdProfileRouteRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/profile/$userId/_profile/': {
      id: '/_app/_protected/profile/$userId/_profile/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof AppProtectedProfileUserIdProfileIndexRouteImport
      parentRoute: typeof AppProtectedProfileUserIdProfileRouteRoute
    }
    '/_app/_protected/profile/$userId/lists/$listId': {
      id: '/_app/_protected/profile/$userId/lists/$listId'
      path: '/profile/$userId/lists/$listId'
      fullPath: '/profile/$userId/lists/$listId'
      preLoaderRoute: typeof AppProtectedProfileUserIdListsListIdRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/profile/$userId/_profile/reposts': {
      id: '/_app/_protected/profile/$userId/_profile/reposts'
      path: '/reposts'
      fullPath: '/profile/$userId/reposts'
      preLoaderRoute: typeof AppProtectedProfileUserIdProfileRepostsRouteImport
      parentRoute: typeof AppProtectedProfileUserIdProfileRouteRoute
    }
    '/_app/_protected/profile/$userId/_profile/lists': {
      id: '/_app/_protected/profile/$userId/_profile/lists'
      path: '/lists'
      fullPath: '/profile/$userId/lists'
      preLoaderRoute: typeof AppProtectedProfileUserIdProfileListsRouteImport
      parentRoute: typeof AppProtectedProfileUserIdProfileRouteRoute
    }
    '/_app/_protected/profile/$userId/_profile/activity': {
      id: '/_app/_protected/profile/$userId/_profile/activity'
      path: '/activity'
      fullPath: '/profile/$userId/activity'
      preLoaderRoute: typeof AppProtectedProfileUserIdProfileActivityRouteImport
      parentRoute: typeof AppProtectedProfileUserIdProfileRouteRoute
    }
    '/_app/_protected/profile/$userId/_profile/about': {
      id: '/_app/_protected/profile/$userId/_profile/about'
      path: '/about'
      fullPath: '/profile/$userId/about'
      preLoaderRoute: typeof AppProtectedProfileUserIdProfileAboutRouteImport
      parentRoute: typeof AppProtectedProfileUserIdProfileRouteRoute
    }
  }
}

interface AppProtectedMeNotificationsRouteRouteChildren {
  AppProtectedMeNotificationsFollowRoute: typeof AppProtectedMeNotificationsFollowRoute
  AppProtectedMeNotificationsLikeRoute: typeof AppProtectedMeNotificationsLikeRoute
  AppProtectedMeNotificationsIndexRoute: typeof AppProtectedMeNotificationsIndexRoute
}

const AppProtectedMeNotificationsRouteRouteChildren: AppProtectedMeNotificationsRouteRouteChildren =
  {
    AppProtectedMeNotificationsFollowRoute:
      AppProtectedMeNotificationsFollowRoute,
    AppProtectedMeNotificationsLikeRoute: AppProtectedMeNotificationsLikeRoute,
    AppProtectedMeNotificationsIndexRoute:
      AppProtectedMeNotificationsIndexRoute,
  }

const AppProtectedMeNotificationsRouteRouteWithChildren =
  AppProtectedMeNotificationsRouteRoute._addFileChildren(
    AppProtectedMeNotificationsRouteRouteChildren,
  )

interface AppProtectedProfileUserIdProfileRouteRouteChildren {
  AppProtectedProfileUserIdProfileAboutRoute: typeof AppProtectedProfileUserIdProfileAboutRoute
  AppProtectedProfileUserIdProfileActivityRoute: typeof AppProtectedProfileUserIdProfileActivityRoute
  AppProtectedProfileUserIdProfileListsRoute: typeof AppProtectedProfileUserIdProfileListsRoute
  AppProtectedProfileUserIdProfileRepostsRoute: typeof AppProtectedProfileUserIdProfileRepostsRoute
  AppProtectedProfileUserIdProfileIndexRoute: typeof AppProtectedProfileUserIdProfileIndexRoute
}

const AppProtectedProfileUserIdProfileRouteRouteChildren: AppProtectedProfileUserIdProfileRouteRouteChildren =
  {
    AppProtectedProfileUserIdProfileAboutRoute:
      AppProtectedProfileUserIdProfileAboutRoute,
    AppProtectedProfileUserIdProfileActivityRoute:
      AppProtectedProfileUserIdProfileActivityRoute,
    AppProtectedProfileUserIdProfileListsRoute:
      AppProtectedProfileUserIdProfileListsRoute,
    AppProtectedProfileUserIdProfileRepostsRoute:
      AppProtectedProfileUserIdProfileRepostsRoute,
    AppProtectedProfileUserIdProfileIndexRoute:
      AppProtectedProfileUserIdProfileIndexRoute,
  }

const AppProtectedProfileUserIdProfileRouteRouteWithChildren =
  AppProtectedProfileUserIdProfileRouteRoute._addFileChildren(
    AppProtectedProfileUserIdProfileRouteRouteChildren,
  )

interface AppProtectedRouteRouteChildren {
  AppProtectedEditorRoute: typeof AppProtectedEditorRoute
  AppProtectedSubmissionRoute: typeof AppProtectedSubmissionRoute
  AppProtectedMeNotificationsRouteRoute: typeof AppProtectedMeNotificationsRouteRouteWithChildren
  AppProtectedMePasswordRoute: typeof AppProtectedMePasswordRoute
  AppProtectedMeSettingsRoute: typeof AppProtectedMeSettingsRoute
  AppProtectedProfileUserIdProfileRouteRoute: typeof AppProtectedProfileUserIdProfileRouteRouteWithChildren
  AppProtectedArticlesEditArticleIdRoute: typeof AppProtectedArticlesEditArticleIdRoute
  AppProtectedProfileUserIdFollowersRoute: typeof AppProtectedProfileUserIdFollowersRoute
  AppProtectedProfileUserIdFollowingRoute: typeof AppProtectedProfileUserIdFollowingRoute
  AppProtectedProfileUserIdListsListIdRoute: typeof AppProtectedProfileUserIdListsListIdRoute
}

const AppProtectedRouteRouteChildren: AppProtectedRouteRouteChildren = {
  AppProtectedEditorRoute: AppProtectedEditorRoute,
  AppProtectedSubmissionRoute: AppProtectedSubmissionRoute,
  AppProtectedMeNotificationsRouteRoute:
    AppProtectedMeNotificationsRouteRouteWithChildren,
  AppProtectedMePasswordRoute: AppProtectedMePasswordRoute,
  AppProtectedMeSettingsRoute: AppProtectedMeSettingsRoute,
  AppProtectedProfileUserIdProfileRouteRoute:
    AppProtectedProfileUserIdProfileRouteRouteWithChildren,
  AppProtectedArticlesEditArticleIdRoute:
    AppProtectedArticlesEditArticleIdRoute,
  AppProtectedProfileUserIdFollowersRoute:
    AppProtectedProfileUserIdFollowersRoute,
  AppProtectedProfileUserIdFollowingRoute:
    AppProtectedProfileUserIdFollowingRoute,
  AppProtectedProfileUserIdListsListIdRoute:
    AppProtectedProfileUserIdListsListIdRoute,
}

const AppProtectedRouteRouteWithChildren =
  AppProtectedRouteRoute._addFileChildren(AppProtectedRouteRouteChildren)

interface AppRouteRouteChildren {
  AppProtectedRouteRoute: typeof AppProtectedRouteRouteWithChildren
  AppNeedLoginRoute: typeof AppNeedLoginRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArticleArticleIdRoute: typeof AppArticleArticleIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProtectedRouteRoute: AppProtectedRouteRouteWithChildren,
  AppNeedLoginRoute: AppNeedLoginRoute,
  AppIndexRoute: AppIndexRoute,
  AppArticleArticleIdRoute: AppArticleArticleIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
