/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NeedLoginRouteImport } from './routes/needLogin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EmailnameRouteImport } from './routes/$emailname'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeSettingsRouteImport } from './routes/me/settings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedLoginRoute = NeedLoginRouteImport.update({
  id: '/needLogin',
  path: '/needLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailnameRoute = EmailnameRouteImport.update({
  id: '/$emailname',
  path: '/$emailname',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSettingsRoute = MeSettingsRouteImport.update({
  id: '/me/settings',
  path: '/me/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$emailname': typeof EmailnameRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/needLogin': typeof NeedLoginRoute
  '/register': typeof RegisterRoute
  '/me/settings': typeof MeSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$emailname': typeof EmailnameRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/needLogin': typeof NeedLoginRoute
  '/register': typeof RegisterRoute
  '/me/settings': typeof MeSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$emailname': typeof EmailnameRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/needLogin': typeof NeedLoginRoute
  '/register': typeof RegisterRoute
  '/me/settings': typeof MeSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$emailname'
    | '/editor'
    | '/login'
    | '/needLogin'
    | '/register'
    | '/me/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$emailname'
    | '/editor'
    | '/login'
    | '/needLogin'
    | '/register'
    | '/me/settings'
  id:
    | '__root__'
    | '/'
    | '/$emailname'
    | '/editor'
    | '/login'
    | '/needLogin'
    | '/register'
    | '/me/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailnameRoute: typeof EmailnameRoute
  EditorRoute: typeof EditorRoute
  LoginRoute: typeof LoginRoute
  NeedLoginRoute: typeof NeedLoginRoute
  RegisterRoute: typeof RegisterRoute
  MeSettingsRoute: typeof MeSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needLogin': {
      id: '/needLogin'
      path: '/needLogin'
      fullPath: '/needLogin'
      preLoaderRoute: typeof NeedLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$emailname': {
      id: '/$emailname'
      path: '/$emailname'
      fullPath: '/$emailname'
      preLoaderRoute: typeof EmailnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/settings': {
      id: '/me/settings'
      path: '/me/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof MeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailnameRoute: EmailnameRoute,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  NeedLoginRoute: NeedLoginRoute,
  RegisterRoute: RegisterRoute,
  MeSettingsRoute: MeSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
