/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppNeedLoginRouteImport } from './routes/_app/needLogin'
import { Route as AppProtectedRouteRouteImport } from './routes/_app/_protected/route'
import { Route as AppProtectedEditorRouteImport } from './routes/_app/_protected/editor'
import { Route as AppProtectedEmailnameRouteImport } from './routes/_app/_protected/$emailname'
import { Route as AppProtectedMeSettingsRouteImport } from './routes/_app/_protected/me/settings'
import { Route as AppProtectedMePasswordRouteImport } from './routes/_app/_protected/me/password'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNeedLoginRoute = AppNeedLoginRouteImport.update({
  id: '/needLogin',
  path: '/needLogin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectedRouteRoute = AppProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectedEditorRoute = AppProtectedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedEmailnameRoute = AppProtectedEmailnameRouteImport.update({
  id: '/$emailname',
  path: '/$emailname',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedMeSettingsRoute = AppProtectedMeSettingsRouteImport.update({
  id: '/me/settings',
  path: '/me/settings',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedMePasswordRoute = AppProtectedMePasswordRouteImport.update({
  id: '/me/password',
  path: '/me/password',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/needLogin': typeof AppNeedLoginRoute
  '/$emailname': typeof AppProtectedEmailnameRoute
  '/editor': typeof AppProtectedEditorRoute
  '/me/password': typeof AppProtectedMePasswordRoute
  '/me/settings': typeof AppProtectedMeSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AppIndexRoute
  '/needLogin': typeof AppNeedLoginRoute
  '/$emailname': typeof AppProtectedEmailnameRoute
  '/editor': typeof AppProtectedEditorRoute
  '/me/password': typeof AppProtectedMePasswordRoute
  '/me/settings': typeof AppProtectedMeSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/_protected': typeof AppProtectedRouteRouteWithChildren
  '/_app/needLogin': typeof AppNeedLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/$emailname': typeof AppProtectedEmailnameRoute
  '/_app/_protected/editor': typeof AppProtectedEditorRoute
  '/_app/_protected/me/password': typeof AppProtectedMePasswordRoute
  '/_app/_protected/me/settings': typeof AppProtectedMeSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/needLogin'
    | '/$emailname'
    | '/editor'
    | '/me/password'
    | '/me/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/needLogin'
    | '/$emailname'
    | '/editor'
    | '/me/password'
    | '/me/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/_protected'
    | '/_app/needLogin'
    | '/_app/'
    | '/_app/_protected/$emailname'
    | '/_app/_protected/editor'
    | '/_app/_protected/me/password'
    | '/_app/_protected/me/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/needLogin': {
      id: '/_app/needLogin'
      path: '/needLogin'
      fullPath: '/needLogin'
      preLoaderRoute: typeof AppNeedLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protected/editor': {
      id: '/_app/_protected/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppProtectedEditorRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/$emailname': {
      id: '/_app/_protected/$emailname'
      path: '/$emailname'
      fullPath: '/$emailname'
      preLoaderRoute: typeof AppProtectedEmailnameRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/me/settings': {
      id: '/_app/_protected/me/settings'
      path: '/me/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AppProtectedMeSettingsRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/me/password': {
      id: '/_app/_protected/me/password'
      path: '/me/password'
      fullPath: '/me/password'
      preLoaderRoute: typeof AppProtectedMePasswordRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
  }
}

interface AppProtectedRouteRouteChildren {
  AppProtectedEmailnameRoute: typeof AppProtectedEmailnameRoute
  AppProtectedEditorRoute: typeof AppProtectedEditorRoute
  AppProtectedMePasswordRoute: typeof AppProtectedMePasswordRoute
  AppProtectedMeSettingsRoute: typeof AppProtectedMeSettingsRoute
}

const AppProtectedRouteRouteChildren: AppProtectedRouteRouteChildren = {
  AppProtectedEmailnameRoute: AppProtectedEmailnameRoute,
  AppProtectedEditorRoute: AppProtectedEditorRoute,
  AppProtectedMePasswordRoute: AppProtectedMePasswordRoute,
  AppProtectedMeSettingsRoute: AppProtectedMeSettingsRoute,
}

const AppProtectedRouteRouteWithChildren =
  AppProtectedRouteRoute._addFileChildren(AppProtectedRouteRouteChildren)

interface AppRouteRouteChildren {
  AppProtectedRouteRoute: typeof AppProtectedRouteRouteWithChildren
  AppNeedLoginRoute: typeof AppNeedLoginRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProtectedRouteRoute: AppProtectedRouteRouteWithChildren,
  AppNeedLoginRoute: AppNeedLoginRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
